# Generated by Django 5.2.4 on 2025-08-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
    ]
